### PR TITLE
revendor moc-sdk 0.10.27-alpha.6

### PR DESCRIPTION
**Pull request by raghavendra-nataraj**

### CODE REVIEW

**Review by nks5295 — APPROVED** [review]
lgtm

**Comment by nks5295** [comment]
i kicked off this run using the latest build: https://msazure.visualstudio.com/msk8s/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?_a=release-pipeline-progress&releaseId=76329

**Review by nwoodmsft — APPROVED** [review]

**Pull request merged**
