### PR TITLE
Adding pull request auto update

### PR DESCRIPTION
**Pull request by apluchik**

### CODE REVIEW

**Review by madhanrm — APPROVED** [review]

**Comment by pradipd** [comment]
What does this do?

**Comment by madhanrm** [comment]
When a PR gets merged, the other PR gets auto updated and would trigger test pass

**Comment by pradipd** [comment]
So what other PR gets autoupdated?  Cloud-operator?  And what test pass do we trigger?  the appliance test pass?

**Review by nwoodmsft — APPROVED** [review]

**Comment by madhanrm** [comment]
> So what other PR gets autoupdated? Cloud-operator? And what test pass do we trigger? the appliance test pass?

Its only for this repo. 
If another PR from this repo gets merged to master, you dont have to rebase and push your new change in your PR.
This would try to update and merge those changes into your PR and kick the test pass automatically.

**Pull request merged**
