### PR TITLE
Adding VM creation fail event

### PR DESCRIPTION
**Pull request by apluchik**
Adding first event logging; for VM creation failure.

### CODE REVIEW

**Review by JocelynBerrendonner — APPROVED** [review]
I am not an expert on what the recorder does, so please check with Zach and Madhan, otherwise this looks good to me

**Comment by JocelynBerrendonner** [comment]
Note: when adding folks to PR, don't forget to also add microsoft/moc-pr which should include everyone

**Comment by pradipd** [comment]
What does this event look like and where does it go? E.g. is this event going to a log file? is it being uploaded to azure or some other cloud?

**Comment by madhanrm** [comment]
it would be available as part of kubctl get events

**Review by madhanrm — APPROVED** [review]

**Comment by pradipd** [comment]
got it. thanks!

**Comment by zawachte-msft** [comment]
lgtm. @apluchik lets sync up and talk about status and phases.

**Comment by madhanrm** [comment]
Are we adding more error events ?

**Comment by apluchik** [comment]
@madhanrm Yep, I'll submit another PR to add more events now.

**Pull request merged**
