### PR TITLE
Remove VM password.

### PR DESCRIPTION
**Pull request by chengzy1994**

### CODE REVIEW

**Review by raghavendra-nataraj — APPROVED** [review]

**Comment by raghavendra-nataraj** [comment]
@nwoodmsft Please can you review this PR?

**Comment by nwoodmsft** [comment]
I'm ok with it @chengzy1994 / @raghavendra-nataraj but we have some large changes that just merged to this codebase for v1beta1 support and that is being stabilized currently...so let me loop in @nks5295 and @zawachte for sign-off and FYI so that they are aware of this additional change (just in case there is anything we hit during upgrade testing or otherwise).

**Review by zawachte — APPROVED** [review]

**Comment by zawachte** [comment]
> 

signed off. I think we should be good.

**Review by nks5295 — APPROVED** [review]

**Comment by raghavendra-nataraj** [comment]
Thanks @zawachte @nks5295

**Pull request merged**
