### PR TITLE
Update moc-sdk version

### PR DESCRIPTION
**Pull request by raghavendra-nataraj**

### CODE REVIEW

**Comment by raghavendra-nataraj** [comment]
@nwoodmsft Can you please review the PR, it includes the moc-sdk to automatically exit wht the connection is unavailable and sitting on a stale connection

**Comment by nks5295** [comment]
note: the failing test was appliance proxy stage - the release was not using a build that contained the updated pause image version

**Review by nks5295 — APPROVED** [review]

**Comment by nwoodmsft** [comment]
Approving with prior results (as pipelines are having issues currently as we are being moved to a new machine pool). The prior results had some failures related to the known issue Neel called out.

**Pull request merged**
