### PR TITLE
Adding events to AzureStackHCI controllers

### PR DESCRIPTION
**Pull request by apluchik**
Adding several events for logging to the AzureStackHciCluster, AzureStackHciLoadbalancer, AzureStackHciMachine, and AzureStackHciVirtualMachines controllers.

### CODE REVIEW

**Review by JocelynBerrendonner — APPROVED** [review]
LGTM

**Comment by zawachte-msft** [comment]
> /azp run

this pipeline is broken. permissions issues from when the repro went public. still thinking about a solution

**Comment by JocelynBerrendonner** [comment]
> this pipeline is broken. permissions issues from when the repro went public. still thinking about a solution

Oh ok! sorry, I didn't realize. Thanks for clarifying, Zach!

**Pull request merged**
